import type {GridData} from '@/types/gridData';
import type {SliderData, TextSliderData} from 'types/slideDataType';

export interface BackendTypeData {
  id: string;
  name: string;
}

export const BackendTypes = [
  {
    id: 'music_videos',
    name: 'Music Videos',
  },
  {
    id: 'news',
    name: 'News',
  },
  {
    id: 'sports',
    name: 'Sports',
  },
  {
    id: 'arial',
    name: 'Arial',
  },
];

export interface BackendVideoData {
  id: string;
  name: string;
  artist: string;
  genre: string;
  duration: number;
  orgHierarchy: string[];
  type: string;
  folderId?: string;
  rating: string;
  url: string;
}

export interface BackendChannelsData {
  id: string;
  name: string;
  type: string;
  orgHierarchy: string[];
  day: string;
  startTime: string;
  endTime: string;
  items: any[];
}
export interface BackendPlaylistsData {
  id: string;
  name: string;
  type: string;
  orgHierarchy: string[];
  folderId?: string;
  url?: string;
  videos?: BackendVideoData[];
  recent?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface MixData {
  id: string;
  order: number;
  playlist: BackendPlaylistsData;
}

export interface BackendMixesData {
  id: string;
  name: string;
  type: string;
  orgHierarchy: string[];
  folderId?: string;
  url?: string;
  recent?: boolean;
  created_at?: string;
  updated_at?: string;
  mix?: MixData[];
}

export interface PlaylistsData {
  id: string;
  playlist: BackendPlaylistsData | undefined;
  day: string;
  startTime: string;
  endTime: string;
}
export interface BackendSignageData {
  id: string;
  name: string;
  type: string;
  assigned?: {
    area: string;
    venue?: string;
  }[];
  url?: string;
  folderId?: string;
  orgHierarchy: string[];
  created_at?: string;
  updated_at?: string;
  slideData?: SliderData;
  textData?: TextSliderData;
}

export interface BackendScheduleData {
  id: string;
  name: string;
  type: string;
  assigned?: {
    area: string;
    venue?: string;
  }[];
  orgHierarchy: string[];
  folderId?: string;
  created_at?: string;
  updated_at?: string;
  playlistsCount?: number;
  playlists?: PlaylistsData[];
}

export const backendMixesData: BackendMixesData[] = [
  {
    id: '1',
    name: 'Mix 1',
    type: 'mix',
    orgHierarchy: ['Mix 1'],
    url: '/assets/images/mcd1.png',
    mix: [
      {
        id: '1',
        order: 1,
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
      },
      {
        id: '2',
        order: 2,
        playlist: {
          id: '2',
          name: 'Playlist 2',
          type: 'news',
          url: '/assets/images/mcd2.png',
          orgHierarchy: ['Playlist 2'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
      },
      {
        id: '3',
        order: 3,
        playlist: {
          id: '3',
          name: 'Playlist 3',
          type: 'sports',
          url: '/assets/images/mcd3.png',
          orgHierarchy: ['Playlist 3'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
      },
    ],
  },
];

export const backendVideosData: BackendVideoData[] = [
  {
    id: '1',
    name: 'Video 1',
    type: 'video',
    artist: 'Artist 1',
    orgHierarchy: ['Video 1'],
    genre: 'pop',
    duration: 100,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
  {
    id: '2',
    name: 'Video 2',
    orgHierarchy: ['Video 2'],
    type: 'video',
    artist: 'Artist 2',
    genre: 'rock',
    duration: 200,
    rating: 'TV-MA',
    url: '/assets/images/mcd2.png',
  },
  {
    id: '3',
    name: 'Video 3',
    type: 'video',
    artist: 'Artist 3',
    orgHierarchy: ['Video 3'],
    genre: 'hip-hop',
    duration: 300,
    rating: 'TV-14',
    url: '/assets/images/mcd3.png',
  },
  {
    id: '4',
    name: 'Video 4',
    type: 'video',
    artist: 'Artist 4',
    orgHierarchy: ['Video 4'],
    genre: 'country',
    duration: 400,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
  {
    id: '5',
    name: 'Video 5',
    type: 'video',
    artist: 'Artist 5',
    orgHierarchy: ['Video 5'],
    genre: 'pop',
    duration: 500,
    rating: 'TV-MA',
    url: '/assets/images/mcd2.png',
  },
  {
    id: '6',
    name: 'Video 6',
    type: 'video',
    artist: 'Artist 6',
    orgHierarchy: ['Video 6'],
    genre: 'country',
    duration: 600,
    rating: 'TV-14',
    url: '/assets/images/mcd3.png',
  },
  {
    id: '7',
    name: 'Video 7',
    type: 'video',
    artist: 'Artist 7',
    orgHierarchy: ['Video 7'],
    genre: 'rock',
    duration: 700,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
  {
    id: '8',
    name: 'Video 8',
    type: 'video',
    artist: 'Artist 8',
    orgHierarchy: ['Video 8'],
    genre: 'country',
    duration: 800,
    rating: 'TV-MA',
    url: '/assets/images/mcd2.png',
  },
  {
    id: '9',
    name: 'Video 9',
    type: 'video',
    artist: 'Artist 9',
    orgHierarchy: ['Video 9'],
    genre: 'hip-hop',
    duration: 900,
    rating: 'TV-14',
    url: '/assets/images/mcd3.png',
  },
  {
    id: '10',
    name: 'Video 10',
    type: 'video',
    artist: 'Artist 10',
    orgHierarchy: ['Video 10'],
    genre: 'pop',
    duration: 1000,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
  {
    id: '11',
    name: 'Video 11',
    type: 'video',
    artist: 'Artist 11',
    orgHierarchy: ['Video 11'],
    genre: 'rock',
    duration: 1100,
    rating: 'TV-MA',
    url: '/assets/images/mcd2.png',
  },
  {
    id: '12',
    name: 'Video 12',
    type: 'video',
    artist: 'Artist 12',
    orgHierarchy: ['Video 12'],
    genre: 'pop',
    duration: 1200,
    rating: 'TV-14',
    url: '/assets/images/mcd3.png',
  },
  {
    id: '13',
    name: 'Video 13',
    type: 'video',
    artist: 'Artist 13',
    orgHierarchy: ['Video 13'],
    genre: 'hip-hop',
    duration: 1300,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
  {
    id: '14',
    name: 'Video 14',
    type: 'video',
    artist: 'Artist 14',
    orgHierarchy: ['Video 14'],
    genre: 'jazz',
    duration: 1400,
    rating: 'TV-MA',
    url: '/assets/images/mcd2.png',
  },
  {
    id: '15',
    name: 'Video 15',
    type: 'video',
    artist: 'Artist 15',
    orgHierarchy: ['Video 15'],
    genre: 'classical',
    duration: 1500,
    rating: 'TV-14',
    url: '/assets/images/mcd3.png',
  },
  {
    id: '16',
    name: 'Video 16',
    type: 'video',
    artist: 'Artist 16',
    orgHierarchy: ['Video 16'],
    genre: 'metal',
    duration: 1600,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
  {
    id: '17',
    name: 'Video 17',
    type: 'video',
    artist: 'Artist 17',
    orgHierarchy: ['Video 17'],
    genre: 'electronic',
    duration: 1700,
    rating: 'TV-MA',
    url: '/assets/images/mcd2.png',
  },
  {
    id: '18',
    name: 'Video 18',
    type: 'video',
    artist: 'Artist 18',
    orgHierarchy: ['Video 18'],
    genre: 'classical',
    duration: 1800,
    rating: 'TV-14',
    url: '/assets/images/mcd3.png',
  },
  {
    id: '19',
    name: 'Video 19',
    type: 'video',
    artist: 'Artist 19',
    orgHierarchy: ['Video 19'],
    genre: 'pop',
    duration: 1900,
    rating: 'TV-PG',
    url: '/assets/images/mcd1.png',
  },
];

export const backendPlaylistsData: BackendPlaylistsData[] = [
  {
    id: 'music_videos',
    name: 'Music Videos',
    type: 'folder',
    orgHierarchy: ['Music Videos'],
  },
  {
    id: 'news',
    name: 'News',
    type: 'folder',
    orgHierarchy: ['News'],
  },
  {
    id: 'sports',
    name: 'Sports',
    type: 'folder',
    orgHierarchy: ['Sports'],
  },
  {
    id: 'arial',
    name: 'Arial',
    type: 'folder',
    orgHierarchy: ['Arial'],
  },
  {
    id: 'test',
    name: 'Test',
    type: 'folder',
    folderId: 'music_videos',
    orgHierarchy: ['Music Videos', 'Test'],
  },
  {
    id: '1',
    name: 'Playlist 1',
    type: 'music_videos',
    folderId: 'music_videos',
    orgHierarchy: ['Music Videos', 'Test', 'Playlist 1'],
    url: '/assets/images/mcd1.png',
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '2',
    name: 'Playlist 2',
    type: 'news',
    folderId: 'news',
    orgHierarchy: ['News', 'Playlist 2'],
    url: '/assets/images/mcd2.png',
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '3',
    name: 'Playlist 3',
    type: 'sports',
    folderId: 'sports',
    orgHierarchy: ['Sports', 'Playlist 3'],
    url: '/assets/images/mcd3.png',
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '4',
    name: 'Playlist 4',
    type: 'arial',
    folderId: 'arial',
    url: '/assets/images/mcd1.png',
    orgHierarchy: ['Arial', 'Playlist 4'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '5',
    name: 'Playlist 5',
    type: 'music_videos',
    folderId: 'music_videos',
    url: '/assets/images/mcd2.png',
    orgHierarchy: ['Music Videos', 'Playlist 5'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '6',
    name: 'Playlist 6',
    type: 'news',
    folderId: 'news',
    url: '/assets/images/mcd3.png',
    orgHierarchy: ['News', 'Playlist 6'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '7',
    name: 'Playlist 7',
    type: 'sports',
    folderId: 'sports',
    url: '/assets/images/mcd1.png',
    orgHierarchy: ['Sports', 'Playlist 7'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '8',
    name: 'Playlist 8',
    type: 'arial',
    folderId: 'arial',
    url: '/assets/images/mcd2.png',
    orgHierarchy: ['Arial', 'Playlist 8'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '9',
    name: 'Playlist 9',
    type: 'music_videos',
    folderId: 'music_videos',
    url: '/assets/images/mcd3.png',
    orgHierarchy: ['Music Videos', 'Playlist 9'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
  {
    id: '10',
    name: 'Playlist 10',
    type: 'news',
    folderId: 'news',
    url: '/assets/images/mcd1.png',
    orgHierarchy: ['News', 'Playlist 10'],
    videos: [
      {
        id: '1',
        name: 'Video 1',
        type: 'video',
        artist: 'Artist 1',
        orgHierarchy: ['Video 1'],
        genre: 'Genre 1',
        duration: 100,
        rating: 'TV-PG',
        url: '/assets/images/mcd1.png',
      },
      {
        id: '2',
        name: 'Video 2',
        type: 'video',
        artist: 'Artist 2',
        orgHierarchy: ['Video 2'],
        genre: 'Genre 2',
        duration: 200,
        rating: 'TV-MA',
        url: '/assets/images/mcd2.png',
      },
      {
        id: '3',
        name: 'Video 3',
        type: 'video',
        artist: 'Artist 3',
        orgHierarchy: ['Video 3'],
        genre: 'Genre 3',
        duration: 300,
        rating: 'TV-14',
        url: '/assets/images/mcd3.png',
      },
    ],
  },
];

export const backendSchedulesData: BackendScheduleData[] = [
  {
    id: '1',
    name: 'Schedule 1',
    type: 'schedule',
    assigned: [
      {
        area: 'southern_california',
        venue: 'burbank',
      },
      {
        area: 'southern_california',
        venue: 'san_diego',
      },
    ],
    orgHierarchy: ['Schedule 1'],
    playlistsCount: 1,
    created_at: '2021-08-09T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    playlists: [
      {
        id: '1',
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T00:00:00',
        endTime: '2022-12-12T05:00:00',
      },
    ],
  },
  {
    id: '2',
    name: 'Schedule 2',
    type: 'schedule',
    orgHierarchy: ['Schedule 2'],
    playlistsCount: 2,
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-11T00:00:00.000Z',
    playlists: [
      {
        id: '1',
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T00:00:00',
        endTime: '2022-12-12T10:00:00',
      },
      {
        id: '2',
        playlist: {
          id: '2',
          name: 'Playlist 2',
          type: 'news',
          url: '/assets/images/mcd2.png',
          orgHierarchy: ['Playlist 2'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '2',
        startTime: '2022-12-12T10:00:00',
        endTime: '2022-12-12T24:00:00',
      },
    ],
  },
  {
    id: '3',
    name: 'Schedule 3',
    type: 'schedule',
    orgHierarchy: ['Schedule 3'],
    playlistsCount: 3,
    created_at: '2021-08-11T00:00:00.000Z',
    updated_at: '2021-08-12T00:00:00.000Z',
    playlists: [
      {
        id: '1',
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T00:00:00',
        endTime: '2022-12-12T04:00:00',
      },
      {
        id: '2',
        playlist: {
          id: '2',
          name: 'Playlist 2',
          type: 'news',
          url: '/assets/images/mcd2.png',
          orgHierarchy: ['Playlist 2'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T04:00:00',
        endTime: '2022-12-12T12:00:00',
      },
      {
        id: '3',
        playlist: {
          id: '3',
          name: 'Playlist 3',
          type: 'sports',
          url: '/assets/images/mcd3.png',
          orgHierarchy: ['Playlist 3'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T12:00:00',
        endTime: '2022-12-12T16:00:00',
      },
    ],
  },
  {
    id: '4',
    name: 'Folder 1',
    type: 'folder',
    orgHierarchy: ['Folder 1'],
  },
  {
    id: '5',
    name: 'Schedule 4',
    type: 'schedule',
    created_at: '2021-08-12T00:00:00.000Z',
    updated_at: '2021-08-13T00:00:00.000Z',
    folderId: '4',
    orgHierarchy: ['Folder 1', 'Schedule 4'],
    playlistsCount: 2,
    playlists: [
      {
        id: '1',
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T00:00:00',
        endTime: '2022-12-12T10:00:00',
      },
      {
        id: '2',
        playlist: {
          id: '2',
          name: 'Playlist 2',
          type: 'news',
          url: '/assets/images/mcd2.png',
          orgHierarchy: ['Playlist 2'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '2',
        startTime: '2022-12-12T10:00:00',
        endTime: '2022-12-12T12:00:00',
      },
    ],
  },
  {
    id: '6',
    name: 'Folder 2',
    type: 'folder',
    orgHierarchy: ['Folder 2'],
  },
  {
    id: '7',
    name: 'Schedule 5',
    type: 'schedule',
    created_at: '2021-08-13T00:00:00.000Z',
    updated_at: '2021-08-14T00:00:00.000Z',
    folderId: '6',
    orgHierarchy: ['Folder 2', 'Schedule 5'],
    playlistsCount: 3,
    playlists: [
      {
        id: '1',
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T20:00:00',
        endTime: '2022-12-12T24:00:00',
      },
      {
        id: '2',
        playlist: {
          id: '2',
          name: 'Playlist 2',
          type: 'news',
          url: '/assets/images/mcd2.png',
          orgHierarchy: ['Playlist 2'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '2',
        startTime: '2022-12-12T10:00:00',
        endTime: '2022-12-12T16:00:00',
      },
      {
        id: '3',
        playlist: {
          id: '3',
          name: 'Playlist 3',
          type: 'sports',
          url: '/assets/images/mcd3.png',
          orgHierarchy: ['Playlist 3'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '3',
        startTime: '2022-12-12T02:00:00',
        endTime: '2022-12-12T10:00:00',
      },
    ],
  },
  {
    id: '8',
    name: 'Schedule 6',
    type: 'schedule',
    created_at: '2021-08-14T00:00:00.000Z',
    updated_at: '2021-08-15T00:00:00.000Z',
    orgHierarchy: ['Schedule 6'],
    playlistsCount: 1,
    playlists: [
      {
        id: '1',
        playlist: {
          id: '1',
          name: 'Playlist 1',
          type: 'music_videos',
          url: '/assets/images/mcd1.png',
          orgHierarchy: ['Playlist 1'],
          videos: [
            {
              id: '1',
              name: 'Video 1',
              type: 'video',
              artist: 'Artist 1',
              orgHierarchy: ['Video 1'],
              genre: 'Genre 1',
              duration: 100,
              rating: 'TV-PG',
              url: '/assets/images/mcd1.png',
            },
            {
              id: '2',
              name: 'Video 2',
              type: 'video',
              artist: 'Artist 2',
              orgHierarchy: ['Video 2'],
              genre: 'Genre 2',
              duration: 200,
              rating: 'TV-MA',
              url: '/assets/images/mcd2.png',
            },
            {
              id: '3',
              name: 'Video 3',
              type: 'video',
              artist: 'Artist 3',
              orgHierarchy: ['Video 3'],
              genre: 'Genre 3',
              duration: 300,
              rating: 'TV-14',
              url: '/assets/images/mcd3.png',
            },
          ],
        },
        day: '1',
        startTime: '2022-12-12T14:00:00',
        endTime: '2022-12-12T18:00:00',
      },
    ],
  },
];

export const backendSignageData: BackendSignageData[] = [
  {
    id: '1',
    name: 'Signage 1',
    type: 'signage',
    url: '/assets/images/mcd1.png',
    orgHierarchy: ['Signage 1'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    slideData: {
      id: '1',
      timing: '1',
      slides: [
        {
          id: '1',
          order: 1,
          data: {
            id: '1',
            name: 'Media 1',
            type: 'image',
            url: '/assets/images/mcd1.png',
            size: 4234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 1'],
          },
        },
        {
          id: '2',
          order: 2,
          data: {
            id: '2',
            name: 'Media 2',
            type: 'image',
            url: '/assets/images/mcd2.png',
            size: 1234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 2'],
          },
        },
      ],
    },
  },
  {
    id: '2',
    name: 'Folder 1',
    type: 'folder',
    orgHierarchy: ['Folder 1'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
  },
  {
    id: '3',
    name: 'Signage 2',
    folderId: '2',
    url: '/assets/images/mcd2.png',
    type: 'signage',
    orgHierarchy: ['Folder 1', 'Signage 2'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    slideData: {
      id: '1',
      timing: '1',
      slides: [
        {
          id: '1',
          order: 1,
          data: {
            id: '1',
            name: 'Media 1',
            type: 'image',
            url: '/assets/images/mcd1.png',
            size: 4234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 1'],
          },
        },
        {
          id: '2',
          order: 2,
          data: {
            id: '2',
            name: 'Media 2',
            type: 'image',
            url: '/assets/images/mcd2.png',
            size: 1234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 2'],
          },
        },
      ],
    },
  },
  {
    id: '4',
    name: 'Folder 2',
    type: 'folder',
    orgHierarchy: ['Folder 2'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
  },
  {
    id: '5',
    name: 'Signage 3',
    folderId: '4',
    url: '/assets/images/mcd3.png',
    type: 'signage',
    orgHierarchy: ['Folder 2', 'Signage 3'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    slideData: {
      id: '1',
      timing: '1',
      slides: [
        {
          id: '1',
          order: 1,
          data: {
            id: '1',
            name: 'Media 1',
            type: 'image',
            url: '/assets/images/mcd1.png',
            size: 4234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 1'],
          },
        },
        {
          id: '2',
          order: 2,
          data: {
            id: '2',
            name: 'Media 2',
            type: 'image',
            url: '/assets/images/mcd2.png',
            size: 1234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 2'],
          },
        },
      ],
    },
  },
  {
    id: '6',
    name: 'Signage 4',
    type: 'signage',
    url: '/assets/images/mcd4.png',
    orgHierarchy: ['Signage 4'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    slideData: {
      id: '1',
      timing: '1',
      slides: [
        {
          id: '1',
          order: 1,
          data: {
            id: '1',
            name: 'Media 1',
            type: 'image',
            url: '/assets/images/mcd1.png',
            size: 4234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 1'],
          },
        },
        {
          id: '2',
          order: 2,
          data: {
            id: '2',
            name: 'Media 2',
            type: 'image',
            url: '/assets/images/mcd2.png',
            size: 1234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 2'],
          },
        },
      ],
    },
  },
  {
    id: '7',
    name: 'Signage 5',
    type: 'signage',
    url: '/assets/images/mcd5.png',
    orgHierarchy: ['Signage 5'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    slideData: {
      id: '1',
      timing: '1',
      slides: [
        {
          id: '1',
          order: 1,
          data: {
            id: '1',
            name: 'Media 1',
            type: 'image',
            url: '/assets/images/mcd1.png',
            size: 4234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 1'],
          },
        },
        {
          id: '2',
          order: 2,
          data: {
            id: '2',
            name: 'Media 2',
            type: 'image',
            url: '/assets/images/mcd2.png',
            size: 1234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 2'],
          },
        },
      ],
    },
  },
  {
    id: '8',
    name: 'Signage 6',
    type: 'signage',
    url: '/assets/images/mcd6.png',
    orgHierarchy: ['Signage 6'],
    created_at: '2021-08-10T00:00:00.000Z',
    updated_at: '2021-08-10T00:00:00.000Z',
    slideData: {
      id: '1',
      timing: '1',
      slides: [
        {
          id: '1',
          order: 1,
          data: {
            id: '1',
            name: 'Media 1',
            type: 'image',
            url: '/assets/images/mcd1.png',
            size: 4234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 1'],
          },
        },
        {
          id: '2',
          order: 2,
          data: {
            id: '2',
            name: 'Media 2',
            type: 'image',
            url: '/assets/images/mcd2.png',
            size: 1234,
            updated_at: '2021-08-10T00:00:00.000Z',
            orgHierarchy: ['Media 2'],
          },
        },
      ],
    },
  },
];

export const backendData: GridData[] = [
  {
    id: '1',
    name: 'Media 1',
    type: 'image',
    url: '/assets/images/mcd1.png',
    size: 4234,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 1'],
  },
  {
    id: '2',
    name: 'Media 2',
    type: 'image',
    url: '/assets/images/mcd2.png',
    size: 1234,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 2'],
  },
  {
    id: '3',
    name: 'Media 3',
    type: 'image',
    url: '/assets/images/mcd3.png',
    size: 2324,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 3'],
  },
  {
    id: '4',
    name: 'Media 4',
    type: 'video',
    thumb: '/assets/images/mcd4.png',
    url: '/assets/images/sample.mp4',
    size: 2141,
    duration: 15,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 4'],
  },
  {
    id: '8',
    name: 'Media 5',
    type: 'text',
    text: 'Text Signage Data',
    size: 4,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 5'],
  },
  {
    id: '10',
    name: 'Media 7',
    type: 'text',
    text: "🍟   Free Fries Now. Free McDonald's Later   🍟",
    size: 3,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 7'],
  },
  {
    id: '11',
    name: 'Media 8',
    type: 'text',
    text: '🍟 Free Fries Now. Free McDonalds Later 🍟',
    size: 5,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 8'],
  },
  {
    id: '14',
    name: 'Media 11',
    type: 'text',
    text: 'The Cardi B & Offset Meal',
    size: 5,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Media 11'],
  },
  {
    id: '5',
    name: 'Folder 1',
    type: 'folder',
    orgHierarchy: ['Folder 1'],
  },
  {
    folderId: '5',
    id: 'folder1_1',
    name: 'Media 1',
    type: 'image',
    url: '/assets/images/mcd5.png',
    size: 4234,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Folder 1', 'Media 1'],
  },
  {
    folderId: '5',
    id: 'folder1_2',
    name: 'Media 2',
    type: 'image',
    url: '/assets/images/mcd6.png',
    size: 2312,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Folder 1', 'Media 2'],
  },
  {
    id: '6',
    name: 'Folder 2',
    type: 'folder',
    orgHierarchy: ['Folder 2'],
  },
  {
    folderId: '6',
    id: 'folder2_1',
    name: 'Media 1',
    type: 'image',
    url: '/assets/images/mcd1.png',
    size: 242,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Folder 2', 'Media 1'],
  },
  {
    folderId: '6',
    id: 'folder2_2',
    name: 'Media 2',
    type: 'image',
    url: '/assets/images/mcd2.png',
    size: 1234,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Folder 2', 'Media 2'],
  },
  {
    id: '7',
    folderId: '6',
    name: 'Folder 3',
    type: 'folder',
    orgHierarchy: ['Folder 2', 'Folder 3'],
  },
  {
    folderId: '7',
    id: 'folder3_1',
    name: 'Media 1',
    type: 'image',
    url: '/assets/images/mcd3.png',
    size: 5312,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Folder 2', 'Folder 3', 'Media 1'],
  },
  {
    folderId: '7',
    id: 'folder3_2',
    name: 'Media 2',
    type: 'image',
    url: '/assets/images/mcd4.png',
    size: 942,
    updated_at: '2021-08-10T00:00:00.000Z',
    orgHierarchy: ['Folder 2', 'Folder 3', 'Media 2'],
  },
];
