export const Zupanije = {
  'Zagrebačka županija': '01',
  'Krapinsko-zagorska županija': '02',
  'Sisačko-moslavačka županija': '03',
  'Karlovačka županija': '04',
  'Varaždinska županija': '05',
  'Koprivničko-križevačka županija': '06',
  'Bjelovarsko-bilogorska županija': '07',
  'Primorsko-goranska županija': '08',
  'Ličko-senjska županija': '09',
  'Virovitičko-podravska županija': '10',
  'Požesko-slavonska županija': '11',
  'Brodsko-posavska županija': '12',
  'Zadarska županija': '13',
  'Osječko-baranjska županija': '14',
  'Šibensko-kninska županija': '15',
  'Vukovarsko-srijemska županija': '16',
  'Splitsko-dalmatinska županija': '17',
  'Istarska županija': '18',
  'Dubrovačko-neretvanska županija': '19',
  'Međimurska županija': '20',
  'Grad Zagreb': '21',
};
